### PR TITLE
Initialize CO2 when not available in initial conditions file

### LINKED ISSUE #779: When CO2 is not in IC file, needs to initialize to a non-zero value
### What happened?

During Cecile's testing ( https://mail.google.com/mail/u/0/#inbox/FMfcgzGsltHJdwHmKsJSkrFBrKzmtmxF ), it was discovered that CO2 initializes to 0 when it is not in an initial condition file.  

Francis proposed the following fix:

In chem_init_cnst we have:

    if ( ghg_chem ) then
       do ilev = 1, nlev
          select case (name)
          case ('N2O')
             where(mask)
                q(:,ilev) = rmwn2o * chem_surfvals_get('N2OVMR')
             end where
          case ('CH4')
             where(mask)
                q(:,ilev) = rmwch4 * chem_surfvals_get('CH4VMR')
             end where
          case ('CFC11')
             where(mask)
                q(:,ilev) = rmwf11 * chem_surfvals_get('F11VMR')
             end where
          case ('CFC12')
             where(mask)
                q(:,ilev) = rmwf12 * chem_surfvals_get('F12VMR')
             end where
          end select
       end do
    end if
So CH4 is being initialized according the the LBC.
It looks like CO2 is being intialized to 1.e-38. It would be easy to add CO2 to the above code block.

Since there is already a 'CO2MMR' option, you could add the case like this:

          case ('CO2')
             where(mask)
                q(:,ilev) = chem_surfvals_get('CO2MMR')
             end where

### What are the steps to reproduce the bug?

See: https://mail.google.com/mail/u/0/#inbox/FMfcgzGsltHJdwHmKsJSkrFBrKzmtmxF

### What CAM tag were you using?

cam6_3_100

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

No

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by cacraigucar**
Closes #779

### CODE REVIEW

**Review by nusbaume — APPROVED** [review]
Whew, this was a tough one!

**Comment by fvitt** [comment]
Do we know if this gives the desired behavior?  I am curious to hear about @cecilehannay 's test with this change.

**Comment by cacraigucar** [comment]
> Do we know if this gives the desired behavior? I am curious to hear about @cecilehannay 's test with this change.

@cecilehannay is just starting up the run.  My plan is to get this PR ready so that if/when she says the code change works, we can bring this in quickly.  I am currently planning on combining this PR with #777 which @brian-eaton is doing the initial review on.   I have added @cecilehannay as a reviewer so she can give us an approval when her job completes and she confirms that CO2 is being initialized as it should be.

**Comment by adamrher** [comment]
@fvitt. @dan800 has confirmed these mods give the desired behavior here: https://github.com/NCAR/amwg_dev/issues/232#issuecomment-1496203672

**Review by brian-eaton — APPROVED** [review]

**Pull request merged**
