### PR TITLE
part of cam6_3_052: Remove dead code

### LINKED ISSUE #458: Duplicate (possibly inconsistent) Lyman-alpha routines in chemistry/mozart
mo_jshort.F90 contains a subroutine `lymana( nlev, o2scol, rmla, ro2la )` called by `jshort_hrates()` and `jshort_photo()`.

The module mo_lymana also contains a subroutine `lymana( o2col, secchi, dto2la, xso2la )` **with a different argument list**. This is called by `set_o2_xsect()` in mo_seto2.F90. The comments for this are cut and paste from the mo_jshort version and are wrong.

Both seem to be using the _Chabrillat and Kockarts "simple parameterization of the absorption of the solar lyman-alpha line," geophysical research letters, vol.24, no.21, pp 2659-2662, 1997_. (note there is a correction to this paper - the table was missing minuses in the exponents). The values of the coefficients in the parameterization are the same, and I believe are consistent with the correction - worth noting in the comments. 

The mo_jshort.F90 version takes the O2 slant column (taking into account spherical geometry using `sphers()` calculated by the `slant_col()` routine), the other version simply the overhead column and a sec(SZA). It's not clear why two versions of the parameterization are needed or why they are provided different estimates of the slant column. It would be good to at least provide a rationale in the comments and/or combine these two subroutines to clean things up.

Hoping Doug Kinnison (ACOM) can resolve this.

### LINKED ISSUE #485: Remove global non-scalable array allocation from mo_drydep
Memory issue in occurs mo_drydep with high-resolution unstructured grids.

In the routine dv_inti_active the following allocate call occurs:
    allocate( index_season_lai(plon,12),stat=astat )

However, it does not seem that index_season_lai is used and moreover it makes the model blow memory since its global non-scalable memory. 

This unused pointer should be removed from mo_drydep.F90

### PR DESCRIPTION
**Pull request by fvitt**
Remove unused dead code related to deprecated xactive_prates (FTUV) photolysis option.

closes #458

### CODE REVIEW

**Review by cacraigucar — APPROVED** [review]
Looks good.  I believe that the description of this PR needs to be modified, as I believe issue #485 has already been brought into cam_development.

I also believe that this PR and #473, will be going in together, correct?

**Comment by fvitt** [comment]
> Looks good. I believe that the description of this PR needs to be modified, as I believe issue #485 has already been brought into cam_development.
> 
> I also believe that this PR and #473, will be going in together, correct?

I updated the description.  
Yes, this can be merged in at the same time as #473.

**Review by nusbaume — APPROVED** [review]
Looks good!  Just one minor (non-required) request.

**Review by gold2718 — APPROVED** [review]
Looks okay, thanks!

**Review by peverwhee — APPROVED** [review]

**Pull request merged**
