### PR TITLE
cam6_3_126: Add MPAS-A 60 and 30km ncdata and related changes

### LINKED ISSUE #847: Add 60 and 30km MPAS-A meshes w/ 32L for analytic ICs
### What is the feature/what would you like to discuss?

In conversation with CESM developers, I have generated ncdata files based on 60 and 30km MPAS-A meshes. These files contain 32 vertical levels and are appropriate only for compsets that use analytic initial conditions and do not expect topography (e.g. FHS94 or FKESSLER).

I have worked on it in [gdicker1:mpasa60and30km_analytic_ncdata](https://github.com/gdicker1/CAM/tree/mpasa60and30km_analytic_ncdata) where I added the proposed paths of these files to `bld/namelist_files/namelist_defaults_cam.xml`. I could use some guidance on the next steps towards a Pull Request, how to address this change in a ChangeLog entry, and any necessary tests.

Extra details:
- This branch is based on tag 'cam6_3_111'. This change is needed for another effort as well, and that tag is a common base.
- I have attempted no formal tests yet - just 10 day runs of FHS94 and FKESSLER compsets that had their ncdata edited.
- As I write this, I'm waiting for help adding these files to the CESM inputdata server. I will update this issue once that has been completed.

### Is there anyone in particular you want to be part of this conversation?

_No response_

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

### PR DESCRIPTION
**Pull request by gdicker1**
This PR modifies the namelist_defaults.xml to add 2 new ncdata files for compsets using 60 and 30km MPAS-A resolutions and analytic initial conditions.

Closes #847

### CODE REVIEW

**Comment by gdicker1** [comment]
This was tested with the following commands, where `testing_inputdata` was a directory I made:
```
./cime/scripts/create_test --output-root testing_cases/ --input-dir testing_inputdata ERP_D_Ln9_Vnuopc_P576.mpasa30z32_mpasa30.FHS94
```

```
./cime/scripts/create_test --output-root testing_cases/ --input-dir testing_inputdata ERP_D_Ln9_Vnuopc_P144.mpasa60z32_mpasa60.FHS94
```

`testing_inputdata` had to be setup with the 4 correct MPAS-A partition files ahead of time. Otherwise no edits were needed for these tests to pass.

**Review by cacraigucar — COMMENTED** [review]
@gdicker1 - I expected to see an update to the MPAS hash/tag in Externals_CAM.cfg as well, based on our discussion today.

**Comment by gdicker1** [comment]
@cacraigucar, this PR was pretty narrow and I'm planning for the update to MPAS v8.0.1 (Issue #861) to be in a different branch/PR.

**Review by cacraigucar — APPROVED** [review]

**Review by nusbaume — APPROVED** [review]

**Review by jtruesdal — APPROVED** [review]
The code looks fine.  Please make sure the new data files have the minimal CAM required metadata before adding to the repo.  For myself I usually run something like this

ncatted -O -a data_title,global,c,c,"MPAS 120 Trop MAM deposition file" $file
ncatted -O -a data_summary,global,c,c,"deposition file remapped from atmsrf_0.23x0.31_181018.nc" $file
ncatted -O -a data_creator,global,c,c,"John Truesdale" $file
ncatted -O -a cesm_contact,global,c,c,"John Truesdale jet@ucar.edu" $file
ncatted -O -a creation_date,global,c,c,"Sep 07 2020" $file

**Comment by gdicker1** [comment]
The most recent force push (3e3b152  to 3f7cfa4 ) rebases this branch onto the current HEAD of cam_development.

**Comment by gdicker1** [comment]
@jtruesdal thanks for the commands! I did have a slight hiccup there, but thanks to help from Cheryl and Chris Fischer I was able to get the correct metadata added.

**Comment by gold2718** [comment]
> The most recent force push ([3e3b152](https://github.com/ESCOMP/CAM/commit/3e3b152e74877ebf9d0959a4cb0ac23c7152c8d7) to [3f7cfa4](https://github.com/ESCOMP/CAM/commit/3f7cfa489e103769355519646b401ba7a17aa136) ) rebases this branch onto the current HEAD of cam_development.

I'm curious. Is it okay now to rebase an open PR? If so, maybe update the workflow?
https://github.com/ESCOMP/CAM/wiki/CAM-SE-Workflows#update-development-branch-from-cam_development-or-release-branch

--Random person working on workflows

**Comment by gdicker1** [comment]
> > The most recent force push ([3e3b152](https://github.com/ESCOMP/CAM/commit/3e3b152e74877ebf9d0959a4cb0ac23c7152c8d7) to [3f7cfa4](https://github.com/ESCOMP/CAM/commit/3f7cfa489e103769355519646b401ba7a17aa136) ) rebases this branch onto the current HEAD of cam_development.
> 
> I'm curious. Is it okay now to rebase an open PR? If so, maybe update the workflow? https://github.com/ESCOMP/CAM/wiki/CAM-SE-Workflows#update-development-branch-from-cam_development-or-release-branch
> 
> --Random person working on workflows

This is my error. I should have rebased before moving this out of draft, didn't, and instead followed the workflow I'm most used to in other projects instead of correctly following what was documented.

**Comment by gold2718** [comment]
No worries (especially since I don't have to review it :)

**Pull request merged**
