### PR TITLE
part of cam6_3_087: mv shr_file to shr_log, fix issue in logunit

### PR DESCRIPTION
**Pull request by jedwards4b**
Fixes issue #720 updates from deprecated shr_file_mod to shr_log_mod.

### CODE REVIEW

**Review by cacraigucar — APPROVED** [review]

**Comment by jedwards4b** [comment]
@cacraigucar I can redo this to use the nuopc mechanism for logunit but that will require a new cmeps tag first.  That cmeps tag isn't ready quite yet.

**Comment by cacraigucar** [comment]
@jedwards4b - I defer to you.  We have a tag that we are making maybe later today or tomorrow.  If you think this change is important to get in right away, we can use what we have.  Otherwise we can just hold off until you make the other changes which we need to coordinate with a CMEPS tag.  Let us know your decision.

**Comment by jedwards4b** [comment]
I think that you should go ahead and merge it then, line 221 is a bug fix.

**Comment by fvitt** [comment]
@jedwards4b @cacraigucar 
Does this require an update to the CESM_share external?

**Comment by cacraigucar** [comment]
> @jedwards4b @cacraigucar Does this require an update to the CESM_share external?

@fvitt - I do not know.  Are you getting errors?  If so, you can back this out and we can add this PR to the one for #730 which will be coming right after yours

**Comment by fvitt** [comment]
> > @jedwards4b @cacraigucar Does this require an update to the CESM_share external?
> 
> @fvitt - I do not know. Are you getting errors? If so, you can back this out and we can add this PR to the one for #730 which will be coming right after yours

The model does not build:
 Cannot find symbol SHR_LOG_SETLOGUNIT in module SHR_LOG_MOD

**Comment by jedwards4b** [comment]
@fvitt yes it does.  Please use share1.0.16

**Comment by cacraigucar** [comment]
@fvitt - Your choice if you want to update the share external or back out this PR.  Let us know which way you proceed

**Comment by fvitt** [comment]
> @fvitt - Your choice if you want to update the share external or back out this PR. Let us know which way you proceed

I will try to use share1.0.16 and let you know how that goes.

**Comment by fvitt** [comment]
> > @fvitt - Your choice if you want to update the share external or back out this PR. Let us know which way you proceed
> 
> I will try to use share1.0.16 and let you know how that goes.

@cacraigucar : Updating to share1.0.6 is working well.  So that is what I am doing for my PR merge.

**Pull request merged**
