### PR TITLE
bugfixes/cleanup clubb_intr, output physics timesteps to log

### PR DESCRIPTION
**Pull request by adamrher**
Fixes https://github.com/ESCOMP/CAM/issues/278
Fixes https://github.com/ESCOMP/CAM/issues/336

To be added to this PR (before first code review):

Fixes https://github.com/ESCOMP/CAM/issues/496
Fixes https://github.com/ESCOMP/CAM/issues/497

### CODE REVIEW

**Review by andrewgettelman — APPROVED** [review]
I've looked at the diags. I concur this is not climate changing. Fine with me.

**Comment by adamrher** [comment]
In tphysac and tphysbc, Is this true:

    real(r8), intent(in) :: ztodt                  ! Two times model timestep (2 delta-t)

I have been assuming it's just 1 physics time-step.

**Comment by adamrher** [comment]
@andrewgettelman you'll need to bring in these changes if you want dp1/dp2 to be part of the PPE runs. Currently they are only recognized in marcop_driver, but we don't use macrop_driver in cam6 (we use clubb_intr).

**Comment by andrewgettelman** [comment]
Thanks Adam for point me to this. I'll make sure @Katetc sees it so we can bring these changes in with the PPE for dp1 and dp2

**Comment by adamrher** [comment]
> In tphysac and tphysbc, Is this true:
> real(r8), intent(in) :: ztodt                  ! Two times model timestep (2 delta-t)

This appears to only be true for the Eulerian dycore. So this comment needs to be modified. Similarly, the physics time-step output to the log needs to be doubled for the Eulerian dycore in this PR (this is b/c for the first time-step, the physics time-step is not doubled; it is only doubled for nstep /= 0).

**Comment by adamrher** [comment]
@andrewgettelman @JulioTBacmeister @swrneale should I include the super-saturation fixes https://github.com/ESCOMP/CAM/issues/351 in the PR?

clubb_l_trapezoidal_rule_zm = .false.
clubb_l_trapezoidal_rule_zt = .false.

It will make this PR climate changing, but seems like it might be timely to just incl. it here. Vince seems to be in agreement, that is, still calling the pdf twice (mid-point & interface levels), but turning off the trapezoidal rules since it overwrites the cloud liquid.

**Comment by andrewgettelman** [comment]
I'm a big fan of including the supersaturation fixes. It's a small change, but cleans it up. Unless you don't want this PR climate changing, and just want to check those changes in in a new PR.

I'm not even sure our procedure for a PR that changes climate with switches and doesn't need SE review....

**Comment by adamrher** [comment]
After speaking with Julio, I've turned off the trapezoidal rules, and added issue https://github.com/ESCOMP/CAM/issues/351 to the original PR post.

**Comment by zarzycki** [comment]
First -- super helpful having the timesteps added to atm.log!

Small bug -- I think timestep logic in physpkg.F90 is missing the below block from clubb_intr that first checks if clubb_timestep is greater than the host (in CAM's case, cldmacmic timestep) and if greater, just sets the two equal.

```
   !  Now check to see if dtime is greater than the host model 
   !    (or sub stepped) time step.  If it is, then simply 
   !    set it equal to the host (or sub step) time step.  
   !    This section is mostly to deal with small host model
   !    time steps (or small sub-steps)

   if (dtime > hdtime) then
     dtime = hdtime
   endif
```

As is, the added diagnostics in physpkg.F90 will give you `clubb_timestep = dt_cldmacmic / 2.`
if you define clubb_timestep > dt_cldmacmic, when it should be `clubb_timestep = dt_cldmacmic`. You can verify this by printing the timesteps in CLUBB.

In physpkg, something like...

```
      clubb_timestep_actual = clubb_timestep
!++
      if (clubb_timestep_actual .gt. cld_macmic_ztodt) then
        clubb_timestep_actual = cld_macmic_ztodt
      endif
!--
      if (mod(cld_macmic_ztodt,clubb_timestep_actual) .ne. 0) then
        clubb_timestep_actual = cld_macmic_ztodt/2._r8
        do while (clubb_timestep_actual > clubb_timestep)
          clubb_timestep_actual = clubb_timestep_actual/2._r8
        end do
      endif
```

should work (TBH, I'd probably rather do an if/else block, but the above matches CLUBB's logic to be safe).

**Comment by adamrher** [comment]
Hey Colin. Good catch. I'll fix that before this is merged.

BTW, the timeline for completing this PR is probably a month out. The other CLUBB PR: https://github.com/ESCOMP/CAM/pull/387 is a higher priority than this one, which we are hoping to begin next week.

**Comment by adamrher** [comment]
@zarzycki while I'm thinking of it ... this could all be avoided if I could just export the relevant physics time-steps around, instead of trying to recreate the time-step calculations in ```physpkg```. The problem is that some of the time-steps are defined during run time proper, i.e., after the initialization phase. And I'm choosing to output the time-steps in the initialization of ```physpkg```. We'll see what Steve and Cheryl think of my approach once we begin code review.

**Comment by adamrher** [comment]
we should consider adding these bug fixes and changes to energy fixer from Oksana: https://github.com/E3SM-Project/E3SM/pull/4490#issuecomment-909616841

**Comment by adamrher** [comment]
closing this PR since I started over with an up to date fork. Will open a new PR.

**Pull request closed without merging**
