### PR TITLE
cam6_3_041:  Fix a couple of issues with recent ZM changes, mods to pass cam_dev ERP tests, misc cam_dev bug fixes,removed unused memory allocation

### LINKED ISSUE #479: Bug when setting zmconv_parcel_pbl=true and using debug
When setting zmconv_parcel_pbl=true with F2000climo compset and running using debug, get the following traceback:

[17]
[17] Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
[17]
[17] Backtrace for this error:
[17] #0  0x7ffb97f943af in ???
[17] #1  0xf7de5a in entropy
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/zm_conv.F90:4667
[17] #2  0xf7e8ac in parcel_dilute
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/zm_conv.F90:4437
[17] #3  0xf80994 in buoyan_dilute
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/zm_conv.F90:4215
[17] #4  0xf960e4 in __zm_conv_MOD_zm_convr
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/zm_conv.F90:802
[17] #5  0xaf9bc0 in __zm_conv_intr_MOD_zm_conv_tend
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/zm_conv_intr.F90:663
[17] #6  0xc5980c in __convect_deep_MOD_convect_deep_tend
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/convect_deep.F90:274
[17] #7  0x6e221a in tphysbc
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/physpkg.F90:2273
[17] #8  0x6f5d1e in __physpkg_MOD_phys_run1
[17]    at /home/cacraig/cam_large_misc_tag/src/physics/cam/physpkg.F90:1150
[17] #9  0x5039b9 in __cam_comp_MOD_cam_run1
[17]    at /home/cacraig/cam_large_misc_tag/src/control/cam_comp.F90:258
[17] #10  0x4fc306 in __atm_comp_mct_MOD_atm_run_mct
[17]    at /home/cacraig/cam_large_misc_tag/src/cpl/mct/atm_comp_mct.F90:522
[17] #11  0x42e81a in __component_mod_MOD_component_run
[17]    at /home/cacraig/cam_large_misc_tag/components/cpl7/driver/main/component_mod.F90:714
[17] #12  0x41614b in __cime_comp_mod_MOD_cime_run
[17]    at /home/cacraig/cam_large_misc_tag/components/cpl7/driver/main/cime_comp_mod.F90:3057
[17] #13  0x42d2f5 in cime_driver
[17]    at /home/cacraig/cam_large_misc_tag/components/cpl7/driver/main/cime_driver.F90:153
[17] #14  0x42d401 in main
[17]    at /home/cacraig/cam_large_misc_tag/components/cpl7/driver/main/cime_driver.F90:23

This feature introduced in  #451 was discovered in testing #387

@adamrher reports that using this setting works fine on cheyenne using intel.  He will need to say if he was using debug or not.

### LINKED ISSUE #485: Remove global non-scalable array allocation from mo_drydep
Memory issue in occurs mo_drydep with high-resolution unstructured grids.

In the routine dv_inti_active the following allocate call occurs:
    allocate( index_season_lai(plon,12),stat=astat )

However, it does not seem that index_season_lai is used and moreover it makes the model blow memory since its global non-scalable memory. 

This unused pointer should be removed from mo_drydep.F90

### LINKED ISSUE #491: cam_dev is failing ERP test
Restarts are not BFB in cam_dev (compare_base_rest failing when running on izumi w/ nag). Run phase is failing for cam_dev (on cheyenne w/ intel and debug=T). Further exploration needs to be done to identify the cause.

### PR DESCRIPTION
**Pull request by cacraigucar**
According to @swrneale:

On cam_development

1. The parcel temperature was set as tl(i) = (hpar(i)-rlqpar(i)-gravparcel_ztop(i))/cp (the parcel vertical mixing scale value) instead of just the environment temperature at the modified parcel launch level tl(i) = t(i,mx(i))

2. There is an incorrect specification of the dp for a layer where the parcel_ztop is found. It includes the surface orographic height when it shouldn't. This should only be a problem over high orography. Over ocean it is unchanged.

Closes #479 

This PR also closes the following separately reviewed PRs:  #493 and #494 

Closes their issues:
Closes #491 
Closes #485

### CODE REVIEW

**Review by gold2718 — APPROVED** [review]
Looks okay. I assume a ChangeLog entry will follow.

**Comment by cacraigucar** [comment]
@gold2718 - Yes, I tend to put together my ChangeLog towards the end of the process, to make sure I accurately capture the files that are being committed.

**Review by peverwhee — APPROVED** [review]

**Review by swrneale — APPROVED** [review]
@cacraigucar this looks good for the merge from my branch.

**Comment by adamrher** [comment]
I suspect another zm error related to the parcel mods occurs when you run a debug=T but using the se-dycore (sometime switching dycore catches a new problem that was previously undetected). From cheryl last night:

"create_test ERP_D_Ln9_Vmct.ne30pg3_ne30pg3_mg17.F2000dev.cheyenne_intel.cam-outfrq9s", it blows up with the following backtrace.

25:MPT:     header=header@entry=0x7fffc0a67a90 "MPT ERROR: Rank 25(g:25) received signal SIGFPE(8).\n\tProcess ID: 37823, Host: r14i0n22, Program: /glade/scratch/cacraig/ERP_D_Ln9_Vmct.ne30pg3_ne30pg3_mg17.F2000dev.cheyenne_intel.cam-outfrq9s.2022010"...) at sig.c:340
25:MPT: #3  0x00002b60151994ff in first_arriver_handler (signo=signo@entry=8,
25:MPT:     stack_trace_sem=stack_trace_sem@entry=0x2b60246a0080) at sig.c:489
25:MPT: #4  0x00002b6015199793 in slave_sig_handler (signo=8, siginfo=<optimized out>,
25:MPT:     extra=<optimized out>) at sig.c:565
25:MPT: #5  <signal handler called>
25:MPT: #6  0x0000000004b2beef in zm_conv::buoyan_dilute (lchnk=22, ncol=6, q=...,
25:MPT:     t=..., p=..., z=..., pf=..., tp=..., qstp=..., tl=..., rl=2501000,
25:MPT:     cape=..., pblt=..., lcl=..., lel=..., lon=..., mx=...,
25:MPT:     rd=287.0423113650487, grav=9.8061600000000002, cp=1004.64, msg=5, zi=...,
25:MPT:     tpert=..., org=<not associated>, landfrac=...)
25:MPT:     at /glade/u/home/cacraig/camdev_restart/src/physics/cam/zm_conv.F90:4135
25:MPT: #7  0x00000000049cca8d in zm_conv::zm_convr (lchnk=22, ncol=6, t=..., qh=...,
25:MPT:     prec=..., jctop=..., jcbot=..., pblh=..., zm=..., geos=..., zi=...,
25:MPT:     qtnd=..., heat=..., pap=..., paph=..., dpp=..., delt=900, mcon=...,
25:MPT:     cme=..., cape=..., tpert=..., dlf=..., pflx=..., zdu=..., rprd=...,
25:MPT:     mu=..., md=..., du=..., eu=..., ed=..., dp=..., dsubcld=..., jt=...,
25:MPT:     maxg=..., ideep=..., ql=..., rliq=..., landfrac=..., org=<not associated>,
25:MPT:     orgt=<not associated>, org2d=<not associated>, dif=..., dnlf=...,
25:MPT:     dnif=..., conv=..., aero=..., rice=...)
25:MPT:     at /glade/u/home/cacraig/camdev_restart/src/physics/cam/zm_conv.F90:797
25:MPT: #8  0x0000000002fd955b in zm_conv_intr::zm_conv_tend (pblh=..., mcon=...,
25:MPT:     cme=..., tpert=..., pflx=..., zdu=..., rliq=..., rice=..., ztodt=1800,
25:MPT:     jctop=..., jcbot=..., state=..., ptend_all=..., landfrac=...,
25:MPT:     pbuf=0x2b7068267cc0)

So we need to discuss whether this should be addressed in this PR or https://github.com/ESCOMP/CAM/pull/493. Or whether to merge both PRs into one.

**Comment by swrneale** [comment]
@adamrher just to be clear, your testing here is with the code in this PR or is it with original ZM parcel PR?

**Comment by adamrher** [comment]
@swrneale the stack traceback that I put in this thread is from a test Cheryl did on Monday evening using the code in this PR. However, I spoke w/ Cheryl this am and she thinks she may have fixed this bug ... so maybe hold off on doing anything until she sends us an updates.

**Comment by cacraigucar** [comment]
I have indeed found the problem, though once it passes this point, it requires the fix in #493 to run to completion .  I will push the change back shortly.  This PR will be combined with #493.

**Review by swrneale — APPROVED** [review]
@cacraigucar looks fine if this was just the problem. The p/ncol design always makes array operations so fraught :) !

**Review by nusbaume — APPROVED** [review]

**Pull request merged**
