### PR TITLE
cam6_2_042: Update clm external to ctsm1.0.dev107; fix input data issue #175

### LINKED ISSUE #175: Correct error checking input_data_utils module
The following correction is needed in input_data_utils module (subroutine set_wghts_indices) to allow for the last time record of an input file when time bounds are used.

--- a/src/chemistry/utils/input_data_utils.F90
+++ b/src/chemistry/utils/input_data_utils.F90
@@ -398,7 +398,7 @@ contains
        endif
     endif
 
-    if (.not.(index>0.and.index<obj%ntimes)) then
+    if (.not.(index>0.and.index<=obj%ntimes)) then
        errmsg = 'input_data_utils::set_wghts_indices cannot not find time indices for input file: '&
             // trim(obj%filename)
        write(iulog,*) trim(errmsg)

### LINKED ISSUE #182: Update to CSTM dev107 to fix FXHIST failing test

### PR DESCRIPTION
**Pull request by fvitt**
modified:   Externals.cfg
        modified:   src/chemistry/utils/input_data_utils.F90

fixes #182 
fixes #175 

NOTE: The majority of aux_cam baseline tests fail due to changes in clm IC file.

### CODE REVIEW

**Comment by fvitt** [comment]
> I've been trying to test FXHIST using cam6_2_040 and dev107 (Basically this PR without the changes in input_data_utils). Both attempts end during the initialization phase. Does the PE layout need to be changed or has this test worked for you without it?

Please specify exactly the test that is failing for you.

**Comment by cacraigucar** [comment]
Doing ./create_test SMS_D_Ln9.f19_f19_mg17.FXHIST.cheyenne_intel.cam-outfrq9s_amie.  This is the aux_cam test we have setup for FXHIST.

**Comment by fvitt** [comment]
> Doing ./create_test SMS_D_Ln9.f19_f19_mg17.FXHIST.cheyenne_intel.cam-outfrq9s_amie. This is the aux_cam test we have setup for FXHIST.

This aux_cam test passed for me more than once... So I don't know.  Do you have a suggestion for an appropriate PE layout?

I am thinking of providing a lnd IC file for this particular test to avoid the need for clm to interpolate the ICs.

**Comment by cacraigucar** [comment]
> > Doing ./create_test SMS_D_Ln9.f19_f19_mg17.FXHIST.cheyenne_intel.cam-outfrq9s_amie. This is the aux_cam test we have setup for FXHIST.
> 
> This aux_cam test passed for me more than once... So I don't know. Do you have a suggestion for an appropriate PE layout?
> 
> I am thinking of providing a lnd IC file for this particular test to avoid the need for clm to interpolate the ICs.

User error on my part for my failing test.  Once I set it up properly, it works.   I would suggest that we test however users will be using the compset.  If they will be interpolating, then we should continue to interpolate.

**Comment by cacraigucar** [comment]
Regarding the comment that most aux_cam tests are failing, I wanted to check that statement with the two main CAM compsets, F2000climo and F1850.  I saw answer changes with F1850 and F2000climo is still BFB.  Is it just runs starting in 1850 that are impacted by the CLM  external change?

**Pull request merged**
