### PR TITLE
improve performance of rh file write

### LINKED ISSUE #1042: write performance of cam rh files
### Issue Type

Infrastructure Update

### Issue Description

Restart history write performance is dreadful due to the ordering of variables in the 
file.  

### Will this change answers?

No

### Will you be implementing this yourself?

Yes

### PR DESCRIPTION
**Pull request by jedwards4b**
Reorders variables in the rh files.  Significantly improves file write performance on derecho.  

Fixes #1042

### CODE REVIEW

**Review by peverwhee — APPROVED** [review]
looks good. Thanks, @jedwards4b !

**Comment by brian-eaton** [comment]
@jedwards4b, I'm getting a regression test failure with this mod.  Starting from current cam_development (cam6_4_014) merge in this PR and run the izumi/nag test:
`ERC_D_Ln9.f10_f10_mg37.QPC6.izumi_nag.cam-outfrq3s_cospsathist`
The run fails (I've repeated the failure 3 times) with the following error reported in cesm.log:
```
Abort with message NetCDF: Start+count exceeds dimension bound in file
/fs/cgd/data0/fischer/ParallelIO/src/clib/pio_darray_int.c at line 998
```
No traceback is reported.
The outfrq3s_cospsathist test uses several history files with various types of output.

**Comment by jedwards4b** [comment]
Thanks - I'll try to reproduce.

**Comment by jedwards4b** [comment]
@brian-eaton I don't think that this is a critical PR - I would suggest that you build the cam tag without it I will debug and update this PR for a future tag.

**Comment by brian-eaton** [comment]
Thanks Jim.  Sounds like a plan.

**Comment by jedwards4b** [comment]
Did you intend to merge this?

**Comment by brian-eaton** [comment]
This PR was originally in the miscellaneous fixes PR #1072 which I just merged.  When I ran into the test failure and isolated it to this PR I pulled it.

**Pull request merged**
