### PR TITLE
CAM SE and  SSTICE bug fixes

### LINKED ISSUE #633: part of cam_cesm2_2_rel_04: Bug in spectral-element advection
### Issue Type

Other (please describe below)

### Issue Description

Bug in spectral-element advection. See details here 

https://github.com/NCAR/amwg_dev/issues/151

Source code modifications to fix bug:

In src/dynamics/se/dycore/prim_advance_mod.F90. replace

               elem(ie)%derived%dpdiss_ave(i,j,k)=elem(ie)%derived%dpdiss_ave(i,j,k)+&
                     rhypervis_subcycle*eta_ave_w*(elem(ie)%state%dp3d(i,j,k,nt)

with

                elem(ie)%derived%dpdiss_ave(i,j,k)=elem(ie)%derived%dpdiss_ave(i,j,k)+&
                     rhypervis_subcycle*eta_ave_w*(elem(ie)%state%dp3d(i,j,k,nt)-elem(ie)%derived%dp_ref(i,j,k))

Source code modification here:

/glade/u/home/pel/src/for-cecille/qdp_ref_bufix/prim_advance_mod.F90

### Will this change answers?

All SE tests  with topography should show significant differences  (round-off or no differences for non-topo  tests such as FKESSLER and QPC). Tests with all other dynamical cores should not show differences.

### Will you be implementing this yourself?

Yes

### LINKED ISSUE #634: SSTICE_GRID_FILENAME and SSTICE_DATA_FILENAME do not belong in config_compsets.xml
### Issue Type

Code Clean-up

### Issue Description

SSTICE_GRID_FILENAME does not belong in nuopc configuraitons.
In addition, I don't understand why these files are here and not in docn. 
I am introducing a new xml variable in cdeps/docn/cime_config which will be SSTICE_MESH_FILENAME that will contain mesh specification for different ocn stream data resolutions. This will replace the SSTICE_GRID_FILENAME and will be used also by cice6 (and cice5).
I am happy to go into more details if that would be helpful.
I will not be implementing the fix in cam - but will be implementing the new capability in docn and cice.

### Will this change answers?

No

### Will you be implementing this yourself?

No

### PR DESCRIPTION
**Pull request by cacraigucar**
Grouping these two answer changing tags together (without the physconst answer changes) to better validate the answer changes.

Closes #633 
Closes #634

### CODE REVIEW

**Review by fvitt — APPROVED** [review]
Looks good to me.  Thank you.

**Review by gold2718 — APPROVED** [review]
Okay

**Review by jtruesdal — APPROVED** [review]
Looks good

**Review by nusbaume — APPROVED** [review]
Thanks for tackling this!

**Comment by cacraigucar** [comment]
@PeterHjortLauritzen sent me an email saying he approved the SE changes

**Pull request merged**
