### PR TITLE
part of cam6_2_046: get pio_file format from driver

### LINKED ISSUE #202: CAM not honoring setting of PIO_NETCDF_FORMAT for hist/rest output.
Setting the PIO_NETCDF_FORMAT is not currently working for CAM and is needed for writing large files.  This issue is associated with pull request #201

### PR DESCRIPTION
**Pull request by jedwards4b**
Get the pio format from the environment variable PIO_NETCDF_FORMAT
Fixes #202.

### CODE REVIEW

**Comment by gold2718** [comment]
I am going to fold this into #200.

**Comment by gold2718** [comment]
@jedwards4b , @jtruesdal , has anyone tried out the changes in this PR?
We have to decide if it goes into the release and it does not seem to compile as is.

**Comment by jedwards4b** [comment]
I think I know what the problem is, but @gold2718 if you could provide more information about the failure it might help.

**Comment by jedwards4b** [comment]
compile issue resolved.

**Comment by gold2718** [comment]
I easily fixed the compile issue in my branch but since the code did not compile, I do not understand how it was tested. Has anyone verified that this PR fixes the problem?

**Comment by jedwards4b** [comment]
Ran test SMS_D.f19_f19.F1850 with PIO_NETCDF_FORMAT='64bit_data' and verified cam file output format.
 ncdump -k run/SMS_D.f19_f19.F1850.cheyenne_intel.20200901_125449_ebam4g.cam.i.0001-01-06-00000.nc
cdf5

**Comment by jtruesdal** [comment]
My test of this code happened before Jim's pull request. I was using the
mods that he gave me a few months ago.

jt

**Comment by gold2718** [comment]
Integrated into cam6_2_046 by #200

**Pull request closed without merging**
