### PR TITLE
cam6_2_009: Mg3smallfixes

### PR DESCRIPTION
**Pull request by Katetc**
The changes address the issues discussed in issue #10 and issue #12 . This includes a change in the history metadata for ADRAIN and ADSNOW, cleaning up "if-statements" so they only apply to mg3 with hail and graupel turned on (no ability to run mg3 without hail or graupel turned on). These changes include fixing two if statements in the radiation code as well. I also removed a test to check tendencies in the case where mg3 is run without hail or graupel. Finally, a warning that checks for "large" in-cloud hail and graupel is removed, because this warning is not scale in-sensitive. Tests with mg3 in high-resolution situations crashed due to large log files created by massive numbers of this warning, even though it is not applicable to those simulations. 

As described in the CAM development workflow, the cam_aux cesm tests have been performed on this branch. All of the Cheyenne tests pass. All of the izumi tests pass except for these two:
DAE.f45_f45_mg37.FHS94.hobart_nag.cam-dae (Overall: FAIL)
SMS_D_Ln9.f19_f19_mg17.FW4madSD.hobart_nag.cam-outfrq9s (Overall: PEND)

For the first one, it fails because zero data assimilation files are found afterwards. I don't know why that is, and it does not seem related to the changes here. If somebody thinks otherwise, I can dig into that further. The second failure is caused by the test hanging just after opening the file: /fs/cgd/csm/inputdata/atm/waccm/lb/LBC_1765-2100_1.9x2.5_CCMI_RCP60_za_c130313.nc, which I think is related to a problem with the compset or this file. Again, if it seems to be related to these mg3 changes, I'd be happy to look into it further.

### CODE REVIEW

**Comment by Katetc** [comment]
So for @gold2718 , the first line of this PR reads: "The changes address the issues discussed in issue #10 and issue #12 ." When you say there should be an issue this is addressing, do you mean something other than what I did there? Unfortunately, I was unable to change any metadata (tags, projects, or assignees) for this PR, due to my permissions. 

Do PR's each need a ChangeLog commit? That's not mentioned in the PR workflow. I thought the ChangeLog would be updated by the developer who makes the actual tag. The PR workflow also only discusses running the CESM aux_cam tests, and not the full CAM test suite. So, that needs to be done still. The ChangeLog asks for the results of the full test suite, so if you want me to do all of that, you should add it to the PR workflow document, please. :)

@brian-eaton No problemo. I'll fix that. :)

**Comment by cacraigucar** [comment]
@katetc - I added you as a developer, so you should be able to assign reviewers, tags and projects now.

**Comment by Katetc** [comment]
@cacraigucar , Yes, "m" is meters. That's the change that Andrew requested in issue #10 . The previous units were incorrect.

**Comment by gold2718** [comment]
@katetc, (breaking this into two pieces):
In order to have GitHub automatically close issues fixed by a PR, you need to use the [proper syntax](https://help.github.com/en/articles/closing-issues-using-keywords). This is mentioned in the [CAM SE Workflow page](https://github.com/NCAR/CAM/wiki/CAM-SE-Workflows) (with which you should familiarize yourself).

**Comment by gold2718** [comment]
> Do PR's each need a ChangeLog commit? That's not mentioned in the PR workflow. I thought the ChangeLog would be updated by the developer who makes the actual tag.

Each tag needs a ChangeLog entry and this PR will have a tag. As for who should write it, it should be the person in the best position to properly document the changes which, in this case, is you (IMHO anyway).

**Comment by nusbaume** [comment]
I went ahead and updated the ESCOMP/CAM wiki specifying that a user should update their own fork's ChangeLog (as I figured it couldn't hurt, and would provide the original developer's description of the changes to be incorporated once the tag is made), and added a step instructing SEs to follow the SE workflow (with a provided link).  Hopefully this will help avoid some of this confusion in the future?

Otherwise, the code changes looks good to me!

**Comment by cacraigucar** [comment]
Chris is having difficulties with an external interacting with CAM, so he is willing to allow the CAM_development branch to move forward with this PR.  If @Katetc  can make sure she has pushed back all of her modifications, then she can notify the reviewers to have another look.  Once approvals have been made she can talk to Brian Eaton (while I'm on PTO) to get the CAM tag number.

**Comment by Katetc** [comment]
Issues resolved #10 and #12 .

**Pull request merged**
