### PR TITLE
ASAP bug fixes for cam_dev restarts and irreproducible results

### LINKED ISSUE #631: irreproducable results in variable resolution
### What happened?

We are seeing intermittent failures of the compset FHIST at resolution ne0np4.NATL.ne30x8_t13

I tried twice at NTASKS=3600 one failed on startup and one ran successfully.
Isla tried at NTASKS=3600 and had two successful runs and one failure.  

Isla tried at NTASKS=5400 and had a similar failure.  I tried at that resolution and had a successful run.

All this to say that I suspect there may be a race condition type problem here and it seems that this compset should be tested more.  

### What are the steps to reproduce the bug?

 ./create_newcase --compset FHIST --res ne0np4.NATL.ne30x8_t13 --case $CASENAME --mach cheyenne --run-unsupported
cd $CASENAME
./xmlchange NTASKS=3600
./case.setup
./case.build
./case.submit 

(maybe that'll work, maybe it won't)

### What CAM tag were you using?

cam6_3_052  (cesm2_3_beta08)

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/jedwards/testRR_jul2022.001

### Will you be addressing this bug yourself?

No

### Extra info

_No response_

### LINKED ISSUE #644: The interpolate_output namelist flag results in bad output values
### What happened?

As reported by @brianpm , a recent CAM simulation with the `ne30pg3_ne30pg3_mg17` and `ne30_g17` grids and the `interpolate_output` namelist flag(s) set to `.true.` resulted in history files with bad/missing values (history variables had O(10^-38) values).  

It should be noted that the non-interpolated history output was fine, so this is likely an issue with the interpolation itself.

### What are the steps to reproduce the bug?

Not entirely sure yet, but based on the example case below it appears that running an F2000climo compset for two days with one of the grids above and the following `user_nl_cam` settings:

```
nhtfrq = 0,-1,-1
mfilt = 1,24,24
ndens = 2,2,2
empty_htapes=.false.
interpolate_output=.true.,.true.,.true.
interpolate_nlat=192,192,192
interpolate_nlon=288,288,288

FINCL2 = 'U','V','T','Q','SOLIN','FSNT','FLUT','PRECC','PRECT'
FINCL3 = 'U','V','T','Q','SOLIN','FSNT','FLUT','PRECC','PRECT'

iradsw = -1
iradlw = -1
use_rad_dt_cosz = .false.
spectralflux = .false.
```

results in the bad history file output.  I will add a comment to this issue if I can find an even simpler setup which produces the same error.

### What CAM tag were you using?

Not sure, but will try with the latest tag and report the results here.

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/work/brianpm/my_cases/test_cases/vanilla.f2000climo.ne30pg3.testinterp02

### Will you be addressing this bug yourself?

Yes

### Extra info

_No response_

### LINKED ISSUE #655: cam_dev is unable to achieve bit-for-bit restarts in numerous configurations
### What happened?

The initial problem of non-bit-for-bit restarts was documented when running ERI_D_Ln18_Vnuopc.ne30pg3_ne30pg3_mg17.F2000dev.cheyenne_intel.cam-outfrq9s

An identical test using F2000climo instead of F2000dev had bit-for-bit restarts

After further testing, it was determined that this test also failed with an FV grid:  ERI_D_Ln18_Vnuopc.f19_f19_mg17.F2000dev.cheyenne_intel.cam-outfrq9s

The same behavior was seen in ERP tests and the very coarse FV grid f10_f10_mg37.  This grid was used extensively to determine a pattern.  The pattern from ERP_D_LnXX_Vnuopc.f10_f10_mg37.F2000dev.cheyenne_intel.cam-outfrq9s is as follows:

(X=fail bit-for-bit, P=passed bit-for-bit and the number is the number of timesteps used in the LnXX testing constraint)

  4....5....6....7....8....9....10....11....12....13....14....15....16....17....18
 X....**P**....X...X....**P....P**.....X......X.......**P......P**......X......X.......**P......P**......X

### What are the steps to reproduce the bug?

./create_test ERP_D_LnXX_Vnuopc.f10_f10_mg37.F2000dev.cheyenne_intel.cam-outfrq9s where XX is the number of timesteps which wish to use

### What CAM tag were you using?

cam6_3_077

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

No

### Extra info

@adamrher - Does this pattern perhaps indicate anything in cam_dev which might be the culprit?

@bstephens82 - Please augment this issue with observations which you have that I may not have already covered.

### PR DESCRIPTION
**Pull request by cacraigucar**
This PR is being closed without fixing as it was determined that since there were unexpected answer changes, each PR/issue would be brought in separately.  This PR does contain the reviews for #660 and #666.

In addition to fixing cam_dev restarts and the irreproducible results issues, this PR will also bring in some interpolate_output SE bug fixes.

#655 was going to be closed
#631 was going to be closed
#658 was going to be closed

#660 was going to be closed
#644 was going to be closed

### CODE REVIEW

**Review by nusbaume — APPROVED** [review]
Looks good to me (ignoring the ChangeLog which I didn't review).  Thanks!

**Review by fvitt — APPROVED** [review]
Seems okay to me.

**Review by peverwhee — APPROVED** [review]

**Review by jtruesdal — APPROVED** [review]
Sorry for the delay just had to brush up on passing optional arguments to a procedure without checking that it is present.  All looks good.

**Comment by adamrher** [comment]
I'm sure this is on someone's todo list, but this PR needs to be cleaned-up. It only needs to address two issues: https://github.com/ESCOMP/CAM/issues/644 and https://github.com/ESCOMP/CAM/pull/658. All others mentioned are addressed through different PRs. Also the "Close #660" should be removed as this is linking to a PR, and not an issue.

**Comment by cacraigucar** [comment]
@adamrher - Yes, this PR morphed from encompassing several issues/PRs to actually being closed without being used at all.  An FYI, if we had used this PR, then it would have been closing issues as well as PRs as it would have brought in #660 along with other changes.  Now each will be in their own PR.  

This PR contains the reviews for #660 and #66

**Pull request closed without merging**
