### PR TITLE
Git fleximod update0.8.2

### LINKED ISSUE #1076: Update to latest git-fleximod
### Issue Type

Infrastructure Update

### Issue Description

Update git-fleximod to v0.8.0

### Will this change answers?

No

### Will you be implementing this yourself?

Yes

### PR DESCRIPTION
**Pull request by jedwards4b**
Updates the git-fleximod subtree to v0.8.0
Fixes  #1076

### CODE REVIEW

**Comment by nusbaume** [comment]
Hi @jedwards4b, I tried your CAM branch with the updated `git-fleximod` version (as I am working on porting it to CAM-SIMA), but ran into the following error:

```
root - ERROR - Failed to checkout CIME/non_py/cprnc False None /home/jnusbaum/SE_projects/jedwards_CAM/cime/CIME/non_py/cprnc CIME/non_py/cprnc
Traceback (most recent call last):
  File "./bin/git-fleximod", line 8, in <module>
    sys.exit(main())
  File "/home/jnusbaum/SE_projects/jedwards_CAM/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 345, in main
    submodules_update(gitmodules, root_dir, fxrequired, force)
  File "/home/jnusbaum/SE_projects/jedwards_CAM/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 251, in submodules_update
    submodules_update(gitsubmodules, repodir, newrequiredlist, force=force)
  File "/home/jnusbaum/SE_projects/jedwards_CAM/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 241, in submodules_update
    submod.update()
  File "/home/jnusbaum/SE_projects/jedwards_CAM/.lib/git-fleximod/git_fleximod/submodule.py", line 366, in update
    f"Failed to checkout {self.name} {repo_exists} {tmpurl} {repodir} {self.path}"
  File "/home/jnusbaum/SE_projects/jedwards_CAM/.lib/git-fleximod/git_fleximod/utils.py", line 130, in fatal_error
    raise RuntimeError("{0}ERROR: {1}".format(os.linesep, message))
RuntimeError: 
ERROR: Failed to checkout CIME/non_py/cprnc False None /home/jnusbaum/SE_projects/jedwards_CAM/cime/CIME/non_py/cprnc CIME/non_py/cprnc
```

Any ideas on how to fix it?  I should note that I don't have this problem if I use `git-fleximod` on the current head of CAM.  Thanks!

**Comment by cacraigucar** [comment]
@jedwards4b - I too get the same error @nusbaume gets:

root - ERROR - Failed to checkout CIME/non_py/cprnc False None /home/cacraig/cam_jim/cime/CIME/non_py/cprnc CIME/non_py/cprnc
Traceback (most recent call last):
  File "/home/cacraig/cam_jim/bin/git-fleximod", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cacraig/cam_jim/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 345, in main
    submodules_update(gitmodules, root_dir, fxrequired, force)
  File "/home/cacraig/cam_jim/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 251, in submodules_update
    submodules_update(gitsubmodules, repodir, newrequiredlist, force=force)
  File "/home/cacraig/cam_jim/.lib/git-fleximod/git_fleximod/git_fleximod.py", line 241, in submodules_update
    submod.update()
  File "/home/cacraig/cam_jim/.lib/git-fleximod/git_fleximod/submodule.py", line 365, in update
    utils.fatal_error(
  File "/home/cacraig/cam_jim/.lib/git-fleximod/git_fleximod/utils.py", line 130, in fatal_error
    raise RuntimeError("{0}ERROR: {1}".format(os.linesep, message))
RuntimeError:
ERROR: Failed to checkout CIME/non_py/cprnc False None /home/cacraig/cam_jim/cime/CIME/non_py/cprnc CIME/non_py/cprnc

**Comment by jedwards4b** [comment]
@cacraigucar I'm working on it this morning and should have a solution ready soon.

**Comment by jedwards4b** [comment]
@nusbaume @cacraigucar give it another try.

**Comment by nusbaume** [comment]
@jedwards4b It works for me now.  Thanks for your help!

**Pull request merged**
