### PR TITLE
Update to the new UCAR contributor code of conduct

### PR DESCRIPTION
**Pull request by ekluzek**
This updates the CAM code of conduct (COC) to the UCAR model version. 

https://doi.org/10.5065/6w2c-a132

I'm not sure if this should just go to this branch or other branches as well. I'm assuming you can bring this in and then push it to other branches that might need it.

The above COC needs to be used on projects with a strong UCAR/NCAR involvement/management. This is also important to have because of NSF funding requirements.

There are a few things added to the list of behaviors. But, it also maps out possible consequences for bad behavior. Even people not working for UCAR can involve UCAR resources to resolve issues.

It would be good for the CAM community to review the list and confirm everyone is onboard with it.

### CODE REVIEW

**Comment by cacraigucar** [comment]
Content has been vetted elsewhere, so the request of the reviewers is to just be aware that this is happening and see if any discussion needed to occur.

**Comment by gold2718** [comment]
Is this the right place for it? I'm not sure that @ekluzek knows that we do not use master for anything. What about the development and release branches?
No issues with the content although the adoption date should be updated (per the instructions in the CoC) and converted to a standard date format (preferably ISO 8601).
Finally, do we want to add a statement that this CoC replaces one that is already in force for CAM? It is similar (also an NCAR/UCAR centric version) based on the same Contributor Covenant version (v1.4).

**Comment by cacraigucar** [comment]
I had expected it would go into the two branches (hence its assignment to the two projects pages).  That said, there is one in master currently, so we should either update it as well, or remove it completely.
Feel free to make the proposed edits if you want.

**Comment by cacraigucar** [comment]
Should we also update the one on master, or should we just remove it from there?

**Comment by gold2718** [comment]
This PR should absolutely be merged because that is the version anyone sees when they go to the ESCOMP/CAM GitHub page. Then, it can easily be added to another branch. For instance (assuming you have a branch called `cam_development` and one called `master` which are tied to the remote branches with the same name):
```
git checkout cam_development
git checkout master -- CODE_OF_CONDUCT.md
git commit CODE_OF_CONDUCT.md -m 'Updated Code of Conduct'
```

**Comment by ekluzek** [comment]
The one thing I'm not sure about is that if you have a COC on master it shows up when you start a PR underneath the window for your description of the PR. I think it uses the one from master by default, but I'm not sure what it does if your default branch isn't master.

And yes I would think this should go to your important branches.

**Comment by cacraigucar** [comment]
> This PR should absolutely be merged because that is the version anyone sees when they go to the ESCOMP/CAM GitHub page. Then, it can easily be added to another branch. For instance (assuming you have a branch called `cam_development` and one called `master` which are tied to the remote branches with the same name):
> 
> ```
> git checkout cam_development
> git checkout master -- CODE_OF_CONDUCT.md
> git commit CODE_OF_CONDUCT.md -m 'Updated Code of Conduct'
> ```

Can we not just do the "Merge pull request" button on github?

**Comment by gold2718** [comment]
@cacraigucar, can you assign upcoming taggers with adding this to their PR?

**Comment by cacraigucar** [comment]
I have requested that @brian-eaton add this to his upcoming development and release tags that he is currently making.

**Pull request merged**
