### PR TITLE
cam6_4_034: Add missing total energy in physics state from dycore in snapshots and cleanup total water

### LINKED ISSUE #1141: Total energy/water fields missing second dimension in snapshots
### What happened?

The following fields from `physics_state` have two dimensions, but the second dimension is currently not saved in CAM snapshots:
```
te_ini,         &! vertically integrated total (kinetic + static) energy of initial state
te_cur,         &! vertically integrated total (kinetic + static) energy of current state
tw_ini,         &! vertically integrated total water of initial state
tw_cur           ! vertically integrated total water of new state
```

The second dimension is `phys_te_idx` (or 1) to represent CAM physics total energy, and `dyn_te_idx` (or 2) to represent dycore total energy computed in physics.

## Proposed fix

As discussed with @cacraigucar @nusbaume @peverwhee:

Taking `te_ini` as an example (this would be repeated for the 4 variables with issues), I am proposing to:

1. write these fields into separate variables in the CAM snapshot file:
* `state_te_ini_phys` for CAM physics total energy
* `state_te_ini_dyn` for dycore total energy computed in physics
By modifying only the snapshot infra, i.e. `cam_snapshot_common.F90` in CAM (and corresponding read in CAM-SIMA). No other changes to CAM code will be made.

2. Use standard names `vertically_integrated_energies_of_initial_state_in_cam` and `vertically_integrated_energies_of_initial_state_in_dynamics` for `te_ini_phys` and `te_ini_dyn` respectively.

Currently, the CCPP standard name spreadsheet states `te_ini`'s standard name is `vertically_integrated_energies_of_initial_state` (no suffix). CAM-SIMA code reads `state_te_ini` into `vertically_integrated_energies_of_initial_state_in_cam`.

@PeterHjortLauritzen can I ask if these standard names, particularly suffixes (`_in_cam` and `_in_dynamics`) look good to you?

Thanks!

### What are the steps to reproduce the bug?

Save CAM snapshot and observe `state_te_ini`, `state_te_cur`, `state_tw_ini`, `state_tw_cur` fields, which are saved only with `(time, ncol)` dimensions.

### What CAM tag were you using?

cam6_4_028

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by jimmielin**
Closes #1141 

Saves second dimension (dycore formula) of total energy and total water initial and current condition.

Companion PR in CAM-SIMA to read updated snapshot file and updates to standard names: 
https://github.com/ESCOMP/CAM-SIMA/pull/296

### CODE REVIEW

**Review by cacraigucar — APPROVED** [review]
Good job finding and fixing the bug in cam_snapshot

**Comment by cacraigucar** [comment]
@nusbaume - since the changes morphed beyond snapshot code, I am adding you to the reviewer list as I have not reviewed the other changes

**Comment by jimmielin** [comment]
Thanks @cacraigucar, apologies for repurposing the existing branch. I've updated the title. Changelog update will follow shortly.

**Comment by jimmielin** [comment]
Changes rebased on newest `cam_development` (`cam6_4_031`)

**Review by nusbaume — APPROVED** [review]
Thanks for fixing this!

**Pull request merged**
