### PR TITLE
part of cam6_3_056: fixes for SCT tests to pass

### PR DESCRIPTION
**Pull request by mvertens**
This PR updates the Externals.cfg file and also incorporates fixes for the SCT_D_Ln7_Vnuopc.T42_T42_mg17.QPC5.cheyenne_intel.cam-scm_prep to pass.

### CODE REVIEW

**Comment by peverwhee** [comment]
@mvertens Bringing in these changes does fix the aqauplanet/SCAM/NUOPC tests. Thanks! 

However, the corresponding MCT tests are now failing (unable to set up the grid at run time). These were added temporarily until we got the NUOPC tests running. I will be removing the MCT tests, but since we're still technically supporting MCT, I feel uncomfortable with these failures. Of course, @gold2718 and @cacraigucar can tell me otherwise.

An example of the failure can be seen here: /scratch/cluster/courtneyp/aux_cam_gnu_20220428105556/SCT_D_Ln7_Vmct.T42_T42_mg17.QPC6.izumi_gnu.cam-scm_prep_c6.GC.aux_cam_gnu_20220428105556

**Comment by mvertens** [comment]
@jedwards4b - I wonder if this is a CIME issue. Can you please look at this and see if you can spot a problem. I'm happy to help later this afternoon.

**Comment by jedwards4b** [comment]
@peverwhee I'm not able to reproduce this problem, please see /scratch/cluster/jedwards/SCT_D_Ln7_Vmct.T42_T42_mg17.QPC6.izumi_gnu.cam-scm_prep_c6.20220428_133206_zgkx7s

**Comment by peverwhee** [comment]
@jedwards4b thanks for running that. It's not an issue with the alpha09a tag externals. Those seem to work. This is with the updated externals in this PR (which includes, but is not limited to, a more recent cime tag)

**Comment by mvertens** [comment]
@peverwhee - can you please point @jedwards4b to the externals we are using. In particular I am using the latest cime tag that was made - I think that could be the problem.

**Comment by peverwhee** [comment]
@mvertens @jedwards4b the Externals used for this case:

/home/courtneyp/Projects/CAM/Externals.cfg
Relevant differences:
- cime6.0.17
- ccs_config_cesm0.0.26
- cmeps0.13.61
- cdeps0.12.46
- share1.0.11

**Comment by mvertens** [comment]
@jedwards4b - thanks so much for doing this!

**Comment by peverwhee** [comment]
@jedwards4b I may be looking at the wrong thing, but I still see many externals differences in /home/jedwards/cesm2_x_alpha

**Comment by jedwards4b** [comment]
You are looking at the right thing.  cime, cmeps and cdeps, share are on master (or main) which correspond to the lastest tags.   ccs_config matchs

**Comment by jedwards4b** [comment]
I also seem to be able to run correctly from your sandbox:  /scratch/cluster/jedwards/SCT_D_Ln7_Vmct.T42_T42_mg17.QPC6.izumi_gnu.cam-scm_prep_c6.20220428_141938_tgkq4j/

**Comment by peverwhee** [comment]
@jedwards4b Well, that's wild. Thanks, Jim. I'll try to see what's going on.

**Comment by peverwhee** [comment]
@jedwards4b To clarify, the error I'm getting is this (during the RUN stage):

> Exception from case_test: ERROR: Could not initialize Grids

I'm not seeing the cases you linked get to that stage.

**Comment by jedwards4b** [comment]
Okay I think I see the problem:
  errput: modelgrid_aliases_mct.xml:3: element grids: Schemas validity error : Element 'grids', attribute '{http://www.w3.org/XML/1998/namespace}base': The attribute '{http://www.w3.org/XML/1998/namespace}base' is not allowed.
component_grids_mct.xml:3: element domains: Schemas validity error : Element 'domains', attribute '{http://www.w3.org/XML/1998/namespace}base': The attribute '{http://www.w3.org/XML/1998/namespace}base' is not allowed.
maps_mct.xml:3: element gridmaps: Schemas validity error : Element 'gridmaps', attribute '{http://www.w3.org/XML/1998/namespace}base': The attribute '{http://www.w3.org/XML/1998/namespace}base' is not allowed.
/home/jedwards/cesm2_x_alpha/cime/../ccs_config/config_grids_mct.xml fails to validate

**Comment by jedwards4b** [comment]
It appears that the xmllint on izumi is giving different results than that on cheyenne - still investigating.

**Comment by jedwards4b** [comment]
@peverwhee - something is confusing me - it seems like this xmllint problem should affect all tests run on izumi with the latest cime (mct and nuopc), but it seems that some of your tests are okay?

**Comment by peverwhee** [comment]
@jedwards4b Correct. Here's the NAG run: /scratch/cluster/courtneyp/aux_cam_nag_20220428105230

Only the MCT aquaplanet tests seem to be failing (but not the MCT aquaplanet SCAM test, weirdly). Ignoring the DAE test, which is a known failure, the only failure for NAG is  ERP_Ln9_Vmct.ne5pg3_ne5pg3_mg37.QPC6.izumi_nag.cam-outfrq9s_clubbmf

**Comment by jedwards4b** [comment]
To summarize:  The xmllint schema test for Grids is failing on izumi when using cime6.0.17,
If I avoid this schema test by setting schema=None in grids.py the test appears to run correctly.  It's not at all clear to me why any tests work on izumi since this schema check also fails for the nuopc grids.  My suggested solution is to change this from an abort condition to a warning.

**Comment by mvertens** [comment]
@peverwhee - @jedwards4b has put a CIME PR in that will fix this problem. Hopefully, it can get accepted tomorrow. If not - maybe we should do a cime branch so that you can get this CAM PR in.

**Comment by mvertens** [comment]
@jedwards4b - do we have the updated CIME and ccsm_config tags that now fix this problem? If so - can we document these here and @peverwhee can proceed with verifying that the tests now pass?

**Comment by jedwards4b** [comment]
The new ccs is ccs_config_cesm0.0.28, the new cime is cime6.0.20.

**Comment by peverwhee** [comment]
Everything seems to be working now EXCEPT:

The FSCAM cheyenne test with CICE6 (the corresponding CICE5/mct test IS working). I'm getting this error in the PET0 log file:
> 20220429 124914.026 ERROR            PET0 ice_comp_nuopc.F90:539 Attribute incorrect typekind  - Passing error in return code

Here's the case: /glade/scratch/courtneyp/aux_cam_20220429102601/SMS_D_Ln9_Vnuopc.T42_T42.FSCAM.cheyenne_intel.cam-outfrq9s.GC.aux_cam_20220429102601

Any ideas @mvertens ?

**Comment by jedwards4b** [comment]
I think I see the problem.   Testing a fix now.

**Pull request merged**
