### PR TITLE
cam_cesm2_1_rel_54: adding smyle branch

### LINKED ISSUE #256: User-mod directory needed for SMYLE simulations
I need to work with someone to add a user-mod directory for the SMYLE simulations.

Information on the settings is here.

https://docs.google.com/document/d/1rV3fWCIt-D1fAbzQ6uaQeZyLagzzKnopofr88eXegzY/edit?ts=5f7e43e4

I think the only change needed for CAM is to point to a CO2 future scenario file that has the historical period included in it, so that one simulation from 1850-2025 can be done without changing datasets mid-stream.

Who is the person I need to work with for this?

### PR DESCRIPTION
**Pull request by nanr**
Adding the smyle compset for the SMYLE project.  Fixes #256

### CODE REVIEW

**Comment by gold2718** [comment]
@nanr, is it okay if this PR goes in without a regression test to protect the functionality? Is there a quick test that could be run?

**Comment by cacraigucar** [comment]
@nanr  If you add me as a collaborator with write access on your fork of CAM in github, I can write up a ChangeLog and merge it directly from your fork.   I can give you instructions on how to do this if you need that.

**Comment by gold2718** [comment]
@nanr, I want to triple check that you want this to go only into CESM2.1 (i.e., not CESM2.2 or current development).

**Comment by nanr** [comment]
@cacraigucar I think I should add you as a collaborator to my fork, if you tell me how to do that.

**Comment by nanr** [comment]
@gold2718 thanks for checking.  I THINK the smyle branch should not be limited to cesm2.1.  I think that it should be carried through to CESM2.2 / current development, and if so, let me know how to proceed.

**Comment by gold2718** [comment]
@nanr,
We will get it on CESM2.1 very soon. My understanding is that is the starting point for the SMYLE experiments -- is that correct?
We can then schedule it for the other branches. What is the use case for CESM2.2 -- is that part of the experiment plan?
For the CAM development branch, we will probably want a regression test (maybe even prebeta) to make sure nothing gets broken.

**Comment by cacraigucar** [comment]
@nanr   On your github.com/nanr/CAM main page, go to settings.  On the left, you'll see "manage access" .  Click on that and then you should see "add collaborator".  If you give me write access, that will be good.

**Comment by cacraigucar** [comment]
@nanr Please let me know if you'd like to make any changes to the ChangeLog.  Or you can `git pull` , make your own edits and then`git commit` and `git push` your changes back.

**Review by cacraigucar — APPROVED** [review]

**Review by peverwhee — APPROVED** [review]

**Review by nusbaume — APPROVED** [review]

**Review by gold2718 — APPROVED** [review]

**Review by fvitt — APPROVED** [review]

**Comment by cacraigucar** [comment]
@nanr  Please let me know if you are okay with the ChangeLog.  If you have no changes, I can go ahead and merge this into the cesm2_1 branch.

**Comment by nanr** [comment]
@cacraigucar ChangeLog looks good.  I have no changes.  Thanks Cheryl.

**Pull request merged**
