### PR TITLE
cam_cesm2_2_rel_04: 3 bug fixes for CESM2.2 release

### LINKED ISSUE #392: Spectral Element science updates/bug fixes/refactor (aka CESM2.2-updates)
These mods are necessary to fix science bugs, improve algorithms and numerical stability.

Detailed list of mods:

- remove Rayleigh friction in SE dycore (remove namelist and associated code; not used) (src/dynamics/se/dyn_comp.F90, src/dynamics/se/dycore/prim_advance_mod.F90)
- change various namelist changes for time-stepping
 - move outfld of PMID so it is output for dry configurations (src/physics/cam/cam_diagnostics.F90)
- bug fixes for WACCM-x in dp_coupling for species dependent thermodynamics
- remove vertical diffusion code in SE dycore (not used) - (src/dynamics/se/dycore/prim_advance_mod.F90)
- change some idealized tracer fields for dynamical core test suite (cam/physics/tracer.F90)
- PGF (Pressure gradient force) discretization change (use of reference profile) to alleviate noise over steep orography (src/dynamics/se/dycore/prim_advance_mod.F90)
- changes to hyperviscosity on temperature to alleviate noise over steep orography (src/dynamics/se/dycore/viscosity_mod.F90)
- sponge layer changes for stability (increase del4 damping in sponge, i.e. introduce level dependent damping);  (src/dynamics/se/dycore/global_norms_mod.F90; src/dynamics/se/dycore/dimensions_mod.F90)
- bug fixes in physconst.F90 for WACCM-x and SE (mid pressure calculation consistency)
- change namelist defaults so that hi-res and var-res support configurations (ne120, ARCTIC, ARCTCIGRIS, CONUS) aren't running with unnecessarily small CLUBB time-steps
- fix initialization bug in angular momentum diagnostics (src/physics/cam/check_energy.F90)
- print more info to log file (src/dynamics/se/dyn_comp.F90)

All regression tests using SE are expected to fail against baseline.

### LINKED ISSUE #551: Noise in derived quantities in ne30pg3 configuration #551
Issue: Topography induced noise in spectral-element physics grid configurations (NOT np4 configurations) in derived quantities such as PSL, eddy Z500, etc.

Reason: Derived quantities are sensitive to how variables are mapped to physics grid. In particular, PHIS is read in on physics grid and mapped (using degree 3 tensor interpolation) to GLL grid but not mapped back to physics grid. Consequently T and PHIS are not "consistent" in terms of both being mapped from GLL to physics grid.

Solution: map PHIS from GLL to physics grid in dp_coupling. This is a one line code change in src/dynamics/se/dycore/fvm_mapping.F90, that is, replace line 452

phis_phys(:,ie) = RESHAPE(fvm(ie)%phis_physgrid,SHAPE(phis_phys(:,ie)))

with

phis_phys(:,ie) = RESHAPE(dyn2phys(elem(ie)%state%phis(:,:),elem(ie)%metdet(:,:),inv_area),SHAPE(phis_phys(:,ie)))

### LINKED ISSUE #633: part of cam_cesm2_2_rel_04: Bug in spectral-element advection
### Issue Type

Other (please describe below)

### Issue Description

Bug in spectral-element advection. See details here 

https://github.com/NCAR/amwg_dev/issues/151

Source code modifications to fix bug:

In src/dynamics/se/dycore/prim_advance_mod.F90. replace

               elem(ie)%derived%dpdiss_ave(i,j,k)=elem(ie)%derived%dpdiss_ave(i,j,k)+&
                     rhypervis_subcycle*eta_ave_w*(elem(ie)%state%dp3d(i,j,k,nt)

with

                elem(ie)%derived%dpdiss_ave(i,j,k)=elem(ie)%derived%dpdiss_ave(i,j,k)+&
                     rhypervis_subcycle*eta_ave_w*(elem(ie)%state%dp3d(i,j,k,nt)-elem(ie)%derived%dp_ref(i,j,k))

Source code modification here:

/glade/u/home/pel/src/for-cecille/qdp_ref_bufix/prim_advance_mod.F90

### Will this change answers?

All SE tests  with topography should show significant differences  (round-off or no differences for non-topo  tests such as FKESSLER and QPC). Tests with all other dynamical cores should not show differences.

### Will you be implementing this yourself?

Yes

### PR DESCRIPTION
**Pull request by cacraigucar**
These changes were made by @PeterHjortLauritzen 

Closes #633 
Closes #551 
Closes #392 (one modification from this issue was brought in here)

### CODE REVIEW

**Review by nusbaume — APPROVED** [review]
Looks good to me!  Should we update the PR description though to make it clear that only one of the many modifications listed in issue #392 has been implemented here?

**Review by gold2718 — APPROVED** [review]
Looks good, thanks!

**Review by jtruesdal — APPROVED** [review]
These look fine.

**Comment by cacraigucar** [comment]
One of the regression tests is failing with the error message:

0: ERROR: dyn_readnl: se_molecular_diff must be zero for CESM2.2.0

The job can be seen at:
/glade/scratch/cacraig/aux_cam_20220819120217/ERP_Ln9.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30.GC.aux_cam_20220819120217

@PeterHjortLauritzen or @jtruesdal - any ideas?  I will investigate, but I suspect one of you may know the solution off the top of your head

**Comment by PeterHjortLauritzen** [comment]
I am surprised there is a WACCM-SE test for CESM2.2 since it was not supported for CESM2.2?

You can either remove the endrun statement in the code or set se_molecular_diff=0.0 in the namelist (might not be stable).

**Comment by cacraigucar** [comment]
@PeterHjortLauritzen and @fvitt - In cam_development, only WACCMX is setting se_molecular_diff to a value other than zero, and in that case it is setting it to 1.

@fvitt - What is your recommendation for the CESM2.2 release code for this particular variable (in light of it being WACCM-SE and maybe not even supported in this version)?

**Comment by PeterHjortLauritzen** [comment]
The damping code for WACCM and WACCM-x has been worked on extensively on cam_development. Since WACCM and WACCM-x is not supported in CESM2.2 and we are not going to back port newer code, I recommend letting go of this test (the code is working correctly since it calls endrun and gives the user the message that this functionality is not supported in CESM2.2)

**Comment by cacraigucar** [comment]
@PeterHjortLauritzen - I agree with leaving the code as it is.  #208 had extensive discussion about this, and I believe leaving this failure as it currently runs is appropriate.

**Pull request merged**
